### ISSUE TITLE
Search bar does not work on mobile

### ISSUE THREAD

**Issue by d1joseph** [d1joseph/RaffleNFT#6]
**Describe the bug**
When viewed on devices with a screen width lesser than 600 px, when clicked, the responsive search button does nothing because:
- it's missing code
- a media query isn't right

**To Reproduce**
1. Run the app in the browser with `npm start`
2. Open your developer tool and view the app in device mode
3. Reduce the screen width to 600px or less until the search bar collapses into the search icon
4. Press the search icon
5. See error

**Expected behavior**
When the search icon is clicked, a search bar will expand from behind the icon

**Comment by cisnejo** [comment]
I would like to be assigned this, please.

**Comment by d1joseph** [comment]
Fix: https://github.com/d1joseph/RaffleNFT/pull/11

Outcome:
![screenshot](https://user-images.githubusercontent.com/49397450/193516050-dd9d3f5d-a615-4430-8782-2d2bf11aca72.JPG)

Thanks @cisnejo
